export interface MenuItemData {
  id: number;
  name: string;
  description: string;
  price: number;
  image: string;
  category: string;
  restaurantId?: string;
  restaurantName?: string;
}

export const menuItems: MenuItemData[] = [
  // ── SHIRO PAN-ASIAN & SUSHI LOUNGE (IDs 101 - 112) ──────────────────────────
  {
    id: 101,
    name: 'Crispy Truffle Edamame Dim Sum',
    description: 'Delicate steamed dumplings stuffed with crushed edamame, water chestnuts, and finished with a fragrant white truffle glaze.',
    price: 499,
    image: '/salad.jpg',
    category: 'Starters',
    restaurantId: 'shiro-experience',
    restaurantName: 'Shiro Pan-Asian & Sushi Lounge',
  },
  {
    id: 102,
    name: 'Spicy Salmon & Tuna Maki Roll',
    description: 'Fresh Atlantic salmon and yellowfin tuna rolled with cucumber, scallions, togarashi spice, and sriracha sesame sauce (8 pcs).',
    price: 799,
    image: '/salad.jpg',
    category: 'Starters',
    restaurantId: 'shiro-experience',
    restaurantName: 'Shiro Pan-Asian & Sushi Lounge',
  },
  {
    id: 103,
    name: 'Chicken Yakitori Skewers',
    description: 'Charcoal-grilled tender chicken skewers glazed with sweet mirin, soy, ginger, and roasted sesame seeds.',
    price: 549,
    image: '/burger.jpg',
    category: 'Starters',
    restaurantId: 'shiro-experience',
    restaurantName: 'Shiro Pan-Asian & Sushi Lounge',
  },
  {
    id: 104,
    name: 'Rock Shrimp Tempura',
    description: 'Golden-fried bite-sized tiger prawns tossed in Shiro spicy creamy dressing with fresh chives and lime.',
    price: 699,
    image: '/salad.jpg',
    category: 'Starters',
    restaurantId: 'shiro-experience',
    restaurantName: 'Shiro Pan-Asian & Sushi Lounge',
  },
  {
    id: 105,
    name: 'Authentic Thai Green Curry',
    description: 'Aromatic coconut broth with bamboo shoots, lemongrass, kaffir lime leaves, Asian greens, and steamed fragrant jasmine rice.',
    price: 749,
    image: '/salad.jpg',
    category: 'Mains',
    restaurantId: 'shiro-experience',
    restaurantName: 'Shiro Pan-Asian & Sushi Lounge',
  },
  {
    id: 106,
    name: 'Slow-Roasted Cantonese Peking Duck',
    description: 'Crispy-skinned roast duck breast served with warm steamed lotus pancakes, julienned cucumber, scallions, and rich hoisin plum reduction.',
    price: 1299,
    image: '/burger.jpg',
    category: 'Mains',
    restaurantId: 'shiro-experience',
    restaurantName: 'Shiro Pan-Asian & Sushi Lounge',
  },
  {
    id: 107,
    name: 'Hibachi Garlic Butter Udon Noodles',
    description: 'Thick Japanese udon wok-tossed with roasted garlic, shiitake mushrooms, baby bok choy, and toasted sesame butter.',
    price: 649,
    image: '/pasta.jpg',
    category: 'Mains',
    restaurantId: 'shiro-experience',
    restaurantName: 'Shiro Pan-Asian & Sushi Lounge',
  },
  {
    id: 108,
    name: 'Balinese Spiced Grilled Red Snapper',
    description: 'Pan-seared coastal snapper fillet marinated in sambal matah, turmeric, and galangal, served over sticky coconut rice.',
    price: 1199,
    image: '/salad.jpg',
    category: 'Mains',
    restaurantId: 'shiro-experience',
    restaurantName: 'Shiro Pan-Asian & Sushi Lounge',
  },
  {
    id: 109,
    name: 'Shiro Chocolate Volcano Cake',
    description: 'Warm dark Belgian chocolate cake with a molten lava core, dusted with cocoa and paired with green tea matcha gelato.',
    price: 499,
    image: '/dessert.jpg',
    category: 'Desserts',
    restaurantId: 'shiro-experience',
    restaurantName: 'Shiro Pan-Asian & Sushi Lounge',
  },
  {
    id: 110,
    name: 'Coconut Mango Sticky Rice',
    description: 'Sweet glutinous rice cooked in rich coconut milk, topped with sliced Alphonso mango and roasted mung beans.',
    price: 429,
    image: '/dessert.jpg',
    category: 'Desserts',
    restaurantId: 'shiro-experience',
    restaurantName: 'Shiro Pan-Asian & Sushi Lounge',
  },
  {
    id: 111,
    name: 'Kyoto Iced Matcha Green Tea',
    description: 'Ceremonial grade Japanese Uji matcha whisked with cold almond milk and a touch of organic agave nectar.',
    price: 299,
    image: '/salad.jpg',
    category: 'Beverages',
    restaurantId: 'shiro-experience',
    restaurantName: 'Shiro Pan-Asian & Sushi Lounge',
  },
  {
    id: 112,
    name: 'Yuzu Mint Sparkling Cooler',
    description: 'Fresh Japanese yuzu citrus muddled with garden mint, sparkling soda, and crushed ice for a refreshing palate cleanser.',
    price: 329,
    image: '/salad.jpg',
    category: 'Beverages',
    restaurantId: 'shiro-experience',
    restaurantName: 'Shiro Pan-Asian & Sushi Lounge',
  },

  // ── LE CIRQUE SIGNATURE (IDs 201 - 212) ──────────────────────────────────────
  {
    id: 201,
    name: 'Black Truffle Burrata & Heirloom Tomatoes',
    description: 'Imported Italian burrata with marinated heirloom tomatoes, aged balsamic reduction, pine nuts, and Umbrian black truffle shavings.',
    price: 799,
    image: '/salad.jpg',
    category: 'Starters',
    restaurantId: 'le-cirque-signature',
    restaurantName: 'Le Cirque Signature',
  },
  {
    id: 202,
    name: 'Classic French Onion Soup',
    description: 'Slow-caramelized sweet shallots and sweet onions in rich beef bone broth, gratinéed with sourdough crouton and aged Gruyère.',
    price: 599,
    image: '/salad.jpg',
    category: 'Starters',
    restaurantId: 'le-cirque-signature',
    restaurantName: 'Le Cirque Signature',
  },
  {
    id: 203,
    name: 'Pan-Seared Hokkaido Scallops',
    description: 'Jumbo sea scallops seared to golden perfection, served with velvety cauliflower purée and crisp pancetta.',
    price: 899,
    image: '/salad.jpg',
    category: 'Starters',
    restaurantId: 'le-cirque-signature',
    restaurantName: 'Le Cirque Signature',
  },
  {
    id: 204,
    name: 'Crispy Calamari with Saffron Aioli',
    description: 'Tender Monterey squid rings lightly breaded in seasoned flour, flash-fried and served with zesty lemon saffron aioli.',
    price: 649,
    image: '/salad.jpg',
    category: 'Starters',
    restaurantId: 'le-cirque-signature',
    restaurantName: 'Le Cirque Signature',
  },
  {
    id: 205,
    name: 'Handmade Pappardelle with Wild Mushroom & Truffle',
    description: 'Silky house-rolled pappardelle ribbons tossed in a rich butter emulsion of porcini, morels, and fresh black winter truffle.',
    price: 999,
    image: '/pasta.jpg',
    category: 'Mains',
    restaurantId: 'le-cirque-signature',
    restaurantName: 'Le Cirque Signature',
  },
  {
    id: 206,
    name: 'Pan-Roasted Chilean Sea Bass',
    description: 'Tender Chilean sea bass served over butter-braised baby leeks, asparagus spears, and a delicate Champagne emulsion.',
    price: 1899,
    image: '/pasta.jpg',
    category: 'Mains',
    restaurantId: 'le-cirque-signature',
    restaurantName: 'Le Cirque Signature',
  },
  {
    id: 207,
    name: 'Herb-Crusted New Zealand Lamb Rack',
    description: 'Succulent oven-roasted rack of lamb with rosemary brioche crust, potato mousseline, and a rich thyme jus.',
    price: 1699,
    image: '/burger.jpg',
    category: 'Mains',
    restaurantId: 'le-cirque-signature',
    restaurantName: 'Le Cirque Signature',
  },
  {
    id: 208,
    name: 'Classic San Marzano Margherita Pizza',
    description: 'Wood-fired Neapolitan pizza with D.O.P San Marzano tomatoes, fior di latte mozzarella, fresh basil, and extra virgin olive oil.',
    price: 849,
    image: '/pizza.jpg',
    category: 'Mains',
    restaurantId: 'le-cirque-signature',
    restaurantName: 'Le Cirque Signature',
  },
  {
    id: 209,
    name: 'Traditional Le Cirque Crème Brûlée',
    description: 'The world-famous signature vanilla custard with a brittle glass-like caramelized sugar crust and fresh berries.',
    price: 549,
    image: '/dessert.jpg',
    category: 'Desserts',
    restaurantId: 'le-cirque-signature',
    restaurantName: 'Le Cirque Signature',
  },
  {
    id: 210,
    name: 'Warm Sticky Toffee Pudding',
    description: 'Moist date sponge infused with dark rum, drenched in hot butterscotch toffee sauce and served with Madagascar vanilla bean ice cream.',
    price: 499,
    image: '/dessert.jpg',
    category: 'Desserts',
    restaurantId: 'le-cirque-signature',
    restaurantName: 'Le Cirque Signature',
  },
  {
    id: 211,
    name: 'Classic Venetian Tiramisu',
    description: 'Savoiardi ladyfingers soaked in dark roast espresso and Amaretto liqueur, layered with cloud-light mascarpone cream and Valrhona cocoa.',
    price: 529,
    image: '/dessert.jpg',
    category: 'Desserts',
    restaurantId: 'le-cirque-signature',
    restaurantName: 'Le Cirque Signature',
  },
  {
    id: 212,
    name: 'Espresso Martini (Mocktail)',
    description: 'Fresh shot of dark roast espresso shaken with vanilla cream and coffee reduction, crowned with roasted Arabica beans.',
    price: 399,
    image: '/salad.jpg',
    category: 'Beverages',
    restaurantId: 'le-cirque-signature',
    restaurantName: 'Le Cirque Signature',
  },

  // ── JAMAVAR ROYAL DINING (IDs 301 - 312) ─────────────────────────────────────
  {
    id: 301,
    name: 'Saffron Spiced Tandoori Paneer Tikka',
    description: 'Organic malai paneer steeped in hung yogurt, Kashmiri saffron, and royal garam masala, grilled over charcoal with bell peppers.',
    price: 599,
    image: '/salad.jpg',
    category: 'Starters',
    restaurantId: 'jamavar-palace',
    restaurantName: 'Jamavar Royal Dining',
  },
  {
    id: 302,
    name: 'Melt-in-Mouth Kakori Seekh Kebab',
    description: 'Legendary Awadhi finely minced mutton kebab seasoned with 24 secret royal spices and rose water, melt-in-mouth tender.',
    price: 849,
    image: '/burger.jpg',
    category: 'Starters',
    restaurantId: 'jamavar-palace',
    restaurantName: 'Jamavar Royal Dining',
  },
  {
    id: 303,
    name: 'Tandoori Tiger Prawns',
    description: 'Jumbo coastal tiger prawns coated in roasted ajwain, yellow chili paste, and lemon butter, charred in clay tandoor.',
    price: 999,
    image: '/salad.jpg',
    category: 'Starters',
    restaurantId: 'jamavar-palace',
    restaurantName: 'Jamavar Royal Dining',
  },
  {
    id: 304,
    name: 'Amritsari Crispy Spiced Fish Tikka',
    description: 'Fresh river sole fish marinated with carom seeds and hand-ground spices, golden fried in gram flour batter.',
    price: 749,
    image: '/salad.jpg',
    category: 'Starters',
    restaurantId: 'jamavar-palace',
    restaurantName: 'Jamavar Royal Dining',
  },
  {
    id: 305,
    name: 'Murgh Makhani (Royal Butter Chicken)',
    description: 'Tender tandoor-roasted chicken simmered in an indulgent satin-smooth tomato gravy infused with white butter and kasoori methi.',
    price: 899,
    image: '/burger.jpg',
    category: 'Mains',
    restaurantId: 'jamavar-palace',
    restaurantName: 'Jamavar Royal Dining',
  },
  {
    id: 306,
    name: 'Raan-e-Jamavar (Slow Braised Lamb Shank)',
    description: 'Signature royal dish: baby lamb shank slow-braised for 8 hours in an aromatic caramelized onion and bone marrow reduction.',
    price: 1499,
    image: '/burger.jpg',
    category: 'Mains',
    restaurantId: 'jamavar-palace',
    restaurantName: 'Jamavar Royal Dining',
  },
  {
    id: 307,
    name: 'Dal Jamavar Simmered 24 Hours & Butter Naan',
    description: 'Black lentils slow cooked overnight on charcoal embers with fresh cream, served with crisp buttered tandoori garlic naan.',
    price: 649,
    image: '/burger.jpg',
    category: 'Mains',
    restaurantId: 'jamavar-palace',
    restaurantName: 'Jamavar Royal Dining',
  },
  {
    id: 308,
    name: 'Awadhi Dum Gosht Biryani',
    description: 'Long grain aged basmati rice cooked on dum in sealed clay pots with marinated mutton, saffron milk, and fried onions.',
    price: 949,
    image: '/burger.jpg',
    category: 'Mains',
    restaurantId: 'jamavar-palace',
    restaurantName: 'Jamavar Royal Dining',
  },
  {
    id: 309,
    name: 'Saffron Infused Kesari Rasmalai',
    description: 'Soft cottage cheese rounds steeped in saffron-cardamom clotted milk, garnished with gold leaf and roasted pistachios.',
    price: 399,
    image: '/dessert.jpg',
    category: 'Desserts',
    restaurantId: 'jamavar-palace',
    restaurantName: 'Jamavar Royal Dining',
  },
  {
    id: 310,
    name: 'Royal Shahi Tukda with Pistachio Rabdi',
    description: 'Ghee-fried brioche steeped in saffron syrup, generously topped with slow-reduced creamy rabdi and silver varq.',
    price: 449,
    image: '/dessert.jpg',
    category: 'Desserts',
    restaurantId: 'jamavar-palace',
    restaurantName: 'Jamavar Royal Dining',
  },
  {
    id: 311,
    name: 'Alphonso Mango Lassi with Cardamom',
    description: 'Thick, creamy yogurt lassi blended with fresh Ratnagiri Alphonso mango pulp and fragrant green cardamom.',
    price: 299,
    image: '/salad.jpg',
    category: 'Beverages',
    restaurantId: 'jamavar-palace',
    restaurantName: 'Jamavar Royal Dining',
  },
  {
    id: 312,
    name: 'Royal Masala Chai with Saffron & Ginger',
    description: 'Full-bodied Assam orthodox tea brewed with fresh crushed ginger, green cardamom, cloves, and Kashmiri saffron strands.',
    price: 199,
    image: '/salad.jpg',
    category: 'Beverages',
    restaurantId: 'jamavar-palace',
    restaurantName: 'Jamavar Royal Dining',
  },

  // ── CITRUS MEDITERRANEAN BRASSERIE (IDs 401 - 411) ───────────────────────────
  {
    id: 401,
    name: 'Classic Caesar Salad with Rosemary Chicken',
    description: 'Crisp baby romaine hearts, rosemary-grilled chicken breast, parmesan reggiano tuile, and house anchovy garlic dressing.',
    price: 549,
    image: '/salad.jpg',
    category: 'Starters',
    restaurantId: 'citrus-bistro',
    restaurantName: 'Citrus Mediterranean Brasserie',
  },
  {
    id: 402,
    name: 'Tomato Basil Bruschetta on Sourdough',
    description: 'Crisp sourdough slices rubbed with garlic, topped with vine-ripened tomatoes, fresh basil, and extra virgin olive oil.',
    price: 449,
    image: '/salad.jpg',
    category: 'Starters',
    restaurantId: 'citrus-bistro',
    restaurantName: 'Citrus Mediterranean Brasserie',
  },
  {
    id: 403,
    name: 'Garlic Herb Butter Button Mushrooms',
    description: 'Pan-sautéed whole button mushrooms tossed in French garlic herb butter, white wine, and fresh parsley.',
    price: 499,
    image: '/salad.jpg',
    category: 'Starters',
    restaurantId: 'citrus-bistro',
    restaurantName: 'Citrus Mediterranean Brasserie',
  },
  {
    id: 404,
    name: 'Wood-Fired Prosciutto & Arugula Pizza',
    description: 'Thin crust hand-stretched pizza with San Marzano sauce, fresh mozzarella, thin sliced prosciutto, and peppery wild baby arugula.',
    price: 949,
    image: '/pizza.jpg',
    category: 'Mains',
    restaurantId: 'citrus-bistro',
    restaurantName: 'Citrus Mediterranean Brasserie',
  },
  {
    id: 405,
    name: 'Grilled Atlantic Salmon with Lemon Beurre Blanc',
    description: 'Pan-seared Norwegian salmon steak served with grilled asparagus, crushed baby potatoes, and lemon dill butter sauce.',
    price: 1499,
    image: '/pasta.jpg',
    category: 'Mains',
    restaurantId: 'citrus-bistro',
    restaurantName: 'Citrus Mediterranean Brasserie',
  },
  {
    id: 406,
    name: 'Chicken Fettuccine Alfredo',
    description: 'Fresh fettuccine pasta coated in a luxurious emulsion of heavy cream, aged parmesan, roasted garlic, and grilled herb chicken.',
    price: 799,
    image: '/pasta.jpg',
    category: 'Mains',
    restaurantId: 'citrus-bistro',
    restaurantName: 'Citrus Mediterranean Brasserie',
  },
  {
    id: 407,
    name: 'Four-Cheese Mediterranean Garden Pizza',
    description: 'Artisan wood-fired pizza with gorgonzola, mozzarella, parmesan, goat cheese, kalamata olives, and roasted bell peppers.',
    price: 749,
    image: '/pizza.jpg',
    category: 'Mains',
    restaurantId: 'citrus-bistro',
    restaurantName: 'Citrus Mediterranean Brasserie',
  },
  {
    id: 408,
    name: 'New York Baked Cheesecake with Berry Compote',
    description: 'Dense, velvety smooth cream cheese on a graham cracker crust, topped with fresh raspberry and blueberry compote.',
    price: 499,
    image: '/dessert.jpg',
    category: 'Desserts',
    restaurantId: 'citrus-bistro',
    restaurantName: 'Citrus Mediterranean Brasserie',
  },
  {
    id: 409,
    name: 'Vanilla Bean Panna Cotta',
    description: 'Chilled Italian cream pudding infused with whole Madagascar vanilla pod, topped with tangy passionfruit coulis.',
    price: 449,
    image: '/dessert.jpg',
    category: 'Desserts',
    restaurantId: 'citrus-bistro',
    restaurantName: 'Citrus Mediterranean Brasserie',
  },
  {
    id: 410,
    name: 'Cold Brew Tonic with Citrus Zest',
    description: '18-hour cold brew Arabica coffee paired with tonic water and fresh orange peel over clear ice.',
    price: 299,
    image: '/salad.jpg',
    category: 'Beverages',
    restaurantId: 'citrus-bistro',
    restaurantName: 'Citrus Mediterranean Brasserie',
  },
  {
    id: 411,
    name: 'Freshly Pressed Watermelon Mint Refresher',
    description: 'Cold-pressed sweet watermelon juice served with fresh mint leaves, lime juice, and a pinch of black salt.',
    price: 249,
    image: '/salad.jpg',
    category: 'Beverages',
    restaurantId: 'citrus-bistro',
    restaurantName: 'Citrus Mediterranean Brasserie',
  },

  // ── CLASSIC POPULAR DISHES (IDs 1 - 40 for backward compatibility) ───────────
  { id: 1,  name: 'Classic Caesar Salad', description: 'Crisp romaine lettuce with grilled chicken, crunchy croutons, shaved parmesan, and house Caesar dressing.', price: 349, image: '/salad.jpg', category: 'Starters' },
  { id: 2,  name: 'Paneer Tikka', description: 'Soft cottage cheese marinated in spiced yogurt, char-grilled in a tandoor and served with mint chutney.', price: 449, image: '/salad.jpg', category: 'Starters' },
  { id: 3,  name: 'Crispy Calamari', description: 'Tender squid rings lightly breaded and fried golden, served with a zesty lemon aioli dip.', price: 399, image: '/salad.jpg', category: 'Starters' },
  { id: 4,  name: 'Tomato Bruschetta', description: 'Toasted sourdough topped with vine-ripened tomatoes, fresh basil, garlic, and extra-virgin olive oil.', price: 249, image: '/salad.jpg', category: 'Starters' },
  { id: 5,  name: 'Garlic Butter Mushrooms', description: 'Sautéed button mushrooms in garlic-herb butter sauce, served on toasted artisan bread.', price: 299, image: '/salad.jpg', category: 'Starters' },
  { id: 6,  name: 'Chicken Lollipop', description: 'Spicy Indo-Chinese style chicken lollipops with a crispy coating, served with sweet chilli sauce.', price: 499, image: '/salad.jpg', category: 'Starters' },
  { id: 7,  name: 'Spinach Artichoke Dip', description: 'A warm, creamy dip of spinach and artichokes with melted cheese, served with tortilla chips.', price: 349, image: '/salad.jpg', category: 'Starters' },
  { id: 8,  name: 'Prawn Cocktail', description: 'Chilled tiger prawns with classic Marie Rose sauce on crisp iceberg lettuce — a timeless classic.', price: 549, image: '/salad.jpg', category: 'Starters' },
  { id: 9,  name: 'Spring Rolls (6 pcs)', description: 'Crispy vegetarian spring rolls stuffed with seasoned vegetables, served with sweet chilli dipping sauce.', price: 279, image: '/salad.jpg', category: 'Starters' },
  { id: 10, name: 'French Onion Soup', description: 'Classic slow-caramelised onion soup topped with a thick layer of melted Gruyère cheese and toasted crouton.', price: 329, image: '/salad.jpg', category: 'Starters' },
  { id: 11, name: 'The Signature Double Burger', description: 'A towering gourmet double cheeseburger with fresh lettuce, tomatoes, and melted cheese, served with hand-cut fries.', price: 649, image: '/burger.jpg', category: 'Mains' },
  { id: 12, name: 'Truffle Mushroom Pasta', description: 'Handmade pappardelle tossed in a rich truffle and wild mushroom cream sauce, finished with shaved Parmesan.', price: 849, image: '/pasta.jpg', category: 'Mains' },
  { id: 13, name: 'Rustic Margherita Pizza', description: 'Wood-fired Neapolitan base with San Marzano tomato sauce, bubbling fior di latte mozzarella, and fresh basil.', price: 699, image: '/pizza.jpg', category: 'Mains' },
  { id: 14, name: 'Butter Chicken Curry', description: 'Succulent chicken cooked in a velvety, mildly spiced tomato-butter gravy. Served with garlic naan and basmati rice.', price: 649, image: '/burger.jpg', category: 'Mains' },
  { id: 15, name: 'Grilled Atlantic Salmon', description: 'Premium Atlantic salmon fillet, seared skin-crisp, served with herbed risotto and a lemon beurre blanc.', price: 1199, image: '/pasta.jpg', category: 'Mains' },
  { id: 16, name: 'Lamb Rogan Josh', description: 'Tender slow-braised lamb in an aromatic Kashmiri gravy of whole spices, served with saffron pulao.', price: 899, image: '/burger.jpg', category: 'Mains' },
  { id: 17, name: 'Chicken Alfredo Pasta', description: 'Fettuccine pasta tossed with grilled chicken strips in a rich, creamy Alfredo sauce and topped with herbs.', price: 749, image: '/pasta.jpg', category: 'Mains' },
  { id: 18, name: 'Veggie Supreme Pizza', description: 'Generous toppings of bell peppers, olives, mushrooms, sweet corn, red onion, and jalapeños on a crispy base.', price: 649, image: '/pizza.jpg', category: 'Mains' },
  { id: 19, name: 'Dal Makhani & Naan', description: 'Slow-simmered black lentils in a rich, buttery tomato gravy, served with tandoori naan and jeera rice.', price: 499, image: '/burger.jpg', category: 'Mains' },
  { id: 20, name: 'BBQ Ribs Half Rack', description: 'Slow-cooked pork ribs glazed with smoky BBQ sauce, served with coleslaw and golden French fries.', price: 1099, image: '/burger.jpg', category: 'Mains' },
  { id: 21, name: 'Molten Chocolate Lava Cake', description: 'A warm, decadent chocolate cake with a gooey molten centre, served with a scoop of vanilla bean ice cream.', price: 449, image: '/dessert.jpg', category: 'Desserts' },
  { id: 22, name: 'Gulab Jamun (4 pcs)', description: 'Soft milk-solid dumplings soaked in rose-flavoured sugar syrup, served warm with a sprinkle of pistachios.', price: 249, image: '/dessert.jpg', category: 'Desserts' },
  { id: 23, name: 'Classic Tiramisu', description: 'Layers of espresso-soaked ladyfinger biscuits and mascarpone cream, dusted with rich cocoa powder.', price: 399, image: '/dessert.jpg', category: 'Desserts' },
  { id: 24, name: 'New York Cheesecake', description: 'A dense and creamy baked cheesecake on a buttery Graham cracker crust, topped with a fresh berry compote.', price: 429, image: '/dessert.jpg', category: 'Desserts' },
  { id: 25, name: 'Mango Panna Cotta', description: 'Velvety vanilla panna cotta topped with a vibrant Alphonso mango coulis and served chilled.', price: 379, image: '/dessert.jpg', category: 'Desserts' },
  { id: 26, name: 'Crème Brûlée', description: 'Classic French custard with a perfectly caramelised sugar crust, infused with real vanilla bean.', price: 449, image: '/dessert.jpg', category: 'Desserts' },
  { id: 27, name: 'Sticky Toffee Pudding', description: 'Moist date sponge cake drenched in a warm, buttery toffee sauce, served with clotted cream.', price: 419, image: '/dessert.jpg', category: 'Desserts' },
  { id: 28, name: 'Rasmalai (2 pcs)', description: 'Flattened cottage cheese dumplings soaked in saffron-infused, cardamom milk and garnished with almonds.', price: 299, image: '/dessert.jpg', category: 'Desserts' },
  { id: 29, name: 'Ice Cream Sundae', description: 'Your choice of two scoops of artisan ice cream, topped with hot fudge, whipped cream, and a wafer.', price: 349, image: '/dessert.jpg', category: 'Desserts' },
  { id: 30, name: 'Waffles & Maple Syrup', description: 'Crispy Belgian waffles served with warm maple syrup, fresh strawberries, and a dusting of icing sugar.', price: 399, image: '/dessert.jpg', category: 'Desserts' },
  { id: 31, name: 'Fresh Mango Lassi', description: 'A refreshingly thick and creamy yogurt-based drink blended with ripe Alphonso mangoes and a hint of cardamom.', price: 199, image: '/salad.jpg', category: 'Beverages' },
  { id: 32, name: 'Virgin Mojito', description: 'Fresh lime juice, mint leaves, and sugar muddled together with soda water and crushed ice for a zesty refresher.', price: 229, image: '/salad.jpg', category: 'Beverages' },
  { id: 33, name: 'Cold Brew Coffee', description: 'Smooth, naturally low-acid cold brew steeped for 18 hours and served over ice with a touch of simple syrup.', price: 269, image: '/salad.jpg', category: 'Beverages' },
  { id: 34, name: 'Watermelon Juice', description: 'Freshly pressed watermelon juice served chilled, with a squeeze of lime and a pinch of black salt.', price: 179, image: '/salad.jpg', category: 'Beverages' },
  { id: 35, name: 'Masala Chai', description: 'A strong, fragrant Indian tea brewed with ginger, cardamom, cloves, and cinnamon with full-cream milk.', price: 99, image: '/salad.jpg', category: 'Beverages' },
  { id: 36, name: 'Blueberry Smoothie', description: 'A thick and creamy blend of fresh blueberries, banana, Greek yogurt, and honey, served chilled.', price: 249, image: '/salad.jpg', category: 'Beverages' },
  { id: 37, name: 'Sparkling Lemonade', description: 'Freshly squeezed lemon juice with sugar syrup, mint, and sparkling water — bright, bubbly, and refreshing.', price: 199, image: '/salad.jpg', category: 'Beverages' },
  { id: 38, name: 'Espresso Martini (Mocktail)', description: 'A sophisticated espresso-based mocktail with coffee liqueur syrup, shaken to a perfect frothy head.', price: 299, image: '/salad.jpg', category: 'Beverages' },
  { id: 39, name: 'Rose Sharbat', description: 'A traditional chilled rose syrup drink with basil seeds (sabja), milk, and a squeeze of lime.', price: 149, image: '/salad.jpg', category: 'Beverages' },
  { id: 40, name: 'Pineapple Iced Tea', description: 'Chilled black tea infused with pineapple juice, a touch of honey, and fresh mint over crushed ice.', price: 219, image: '/salad.jpg', category: 'Beverages' },
];
